adding changes

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -34,6 +34,8 @@ env:
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
   ARO_SERVER: ${{ secrets.ARO_SERVER }}
   ARO_TOKEN: ${{ secrets.ARO_TOKEN }}
+  GCP_SERVER: ${{ secrets.GCP_SERVER }}
+  GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
   # 🖊️ EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
   OPENSHIFT_NAMESPACE: ""
 
@@ -78,7 +80,7 @@ jobs:
   rosa-ci-cd:
     # 🖊️ Uncomment this if you are using CRDA scan step above
     # needs: crda-scan
-    name: Build and deploy to OpenShift
+    name: ROSA - Build and deploy to OpenShift
     runs-on: ubuntu-20.04
     environment: production
 
@@ -229,8 +231,8 @@ jobs:
         echo
         echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
 
-  aro-ci-cd:
-    name: Build and deploy to OpenShift
+  aro-deploy:
+    name: ARO - deploy to OpenShift
     runs-on: ubuntu-20.04
     environment: production
     needs: rosa-ci-cd
@@ -244,11 +246,6 @@ jobs:
       uses: redhat-actions/openshift-tools-installer@v1
       with:
         oc: 4
-    
-    - env:
-          OUTPUT1: ${{ needs.aws-ci-cd.outputs.MSVC_IMAGE }}
-          OUTPUT2: ${{ needs.aws-ci-cd.outputs.FEND_IMAGE }}
-      run: echo "$OUTPUT1 $OUTPUT2"
 
     - name: Log in to OpenShift
       uses: redhat-actions/oc-login@v1
@@ -302,5 +299,74 @@ jobs:
         echo "==================================================================================="
         echo
         echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+
+  gcp-ci-cd:
+    name: GCP - deploy to OpenShift
+    runs-on: ubuntu-20.04
+    environment: production
+    needs: rosa-ci-cd
+
+    outputs:
+      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    
+    steps:
+    - name: Install oc
+      uses: redhat-actions/openshift-tools-installer@v1
+      with:
+        oc: 4
+    
+    - name: Log in to OpenShift
+      uses: redhat-actions/oc-login@v1
+      with:
+        openshift_server_url: ${{ env.GCP_SERVER }}
+        openshift_token: ${{ env.GCP_TOKEN }}
+        insecure_skip_tls_verify: true
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    
+    - name: Create and expose app
+      id: deploy-and-expose
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: ${{ env.APP_NAME }}
+        image: ${{needs.rosa-ci-cd.outputs.MSVC_IMAGE}}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
+
+    - name: Create and expose app
+      id: deploy-and-expose-frontend
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: 'ostoy'
+        image: ${{needs.rosa-ci-cd.outputs.FEND_IMAGE}}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
+        build_env: 'MICROSERVICE_NAME=OSTOY_MICROSERVICE'
+    
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    
+    - name: Print application FRONTEND URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose-frontend.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose-frontend.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""  
 
 
