adding another rosa for kicks

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -36,6 +36,8 @@ env:
   ARO_TOKEN: ${{ secrets.ARO_TOKEN }}
   GCP_SERVER: ${{ secrets.GCP_SERVER }}
   GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
+  OPENSHIFT_SERVER_TWO: ${{ secrets.OPENSHIFT_SERVER_TWO }}
+  OPENSHIFT_TOKEN_TWO: ${{ secrets.OPENSHIFT_TOKEN_TWO }}
   ARO_LIVE: ${{ vars.ARO_LIVE }}
   GCP_LIVE: ${{ vars.GCP_LIVE }}
   ROSA_LIVE: ${{ vars.ROSA_LIVE }}
@@ -95,6 +97,7 @@ jobs:
       ARO_LIVE: ${{ env.ARO_LIVE }}
       GCP_LIVE: ${{ env.GCP_LIVE }}
       ROSA_LIVE: ${{ env.ROSA_LIVE }}
+      ROSA_PROD: ${{ env.ROSA_PROD }}
 
     steps:
     - name: Check for required secrets
@@ -404,3 +407,73 @@ jobs:
         echo
         echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""  
 
+  rosa2-ci-cd:
+    name: ROSA Prod deployment
+    if: ${{ vars.ROSA_PROD == 'true' }}
+    runs-on: ubuntu-20.04
+    environment: production
+    needs: [image-ci-cd, rosa-deploy]
+    # needs: [rosa-ci-cd, app-ci-cd]
+    
+    outputs:
+      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    
+    steps:
+    - name: Install oc
+      uses: redhat-actions/openshift-tools-installer@v1
+      with:
+        oc: 4
+    
+    - name: Log in to OpenShift
+      uses: redhat-actions/oc-login@v1
+      with:
+        openshift_server_url: ${{ env.OPENSHIFT_SERVER_TWO }}
+        openshift_token: ${{ env.OPENSHIFT_TOKEN_TWO }}
+        insecure_skip_tls_verify: true
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    
+    - name: Create and expose app - backend
+      id: deploy-and-expose
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: ${{ env.APP_NAME }}
+        image: ${{ needs.image-ci-cd.outputs.MSVC_IMAGE }}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
+
+    - name: Create and expose app - frontend
+      id: deploy-and-expose-frontend
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: 'ostoy'
+        image: ${{ needs.image-ci-cd.outputs.FEND_IMAGE }}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
+        build_env: 'MICROSERVICE_NAME=OSTOY_MICROSERVICE'
+    
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    
+    - name: Print application FRONTEND URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose-frontend.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose-frontend.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""  
